image: Visual Studio 2022
version: 0.8.0.{build}
branches:
  only:
  - master
skip_tags: true
skip_commits:
  message: /\[NAB\]/
configuration: Release
platform: x64
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
- pwsh: >-
    . $env:APPVEYOR_BUILD_FOLDER\DoAutobuild.ps1
artifacts:
- path: ColorChord.NET*autobuild-v*.zip
deploy:
- provider: GitHub
  tag: auto-v$(appveyor_build_version)
  release: Automatic Build v$(appveyor_build_version)
  description: This is an automatic build of the latest commits. Usage is at your own risk. Unless you are actively debugging, it is recommended to use a regular release instead.
  auth_token:
    secure: fIgQpdctIp9szYmG0dfhfD0Cc4/eKQYO7aGXOOYULOB4Bu5SIg6GE+ZRw9kTFNRZ
  artifact: /ColorChord\.NET.*autobuild-v.*\.zip/
  prerelease: true